version: '3'
services:
  postgres-db:
    image: "docker.io/library/postgres:12-alpine"
    container_name: "node-gmp-db"
    environment:
      - POSTGRES_USER=${MIKRO_ORM_USER}
      - POSTGRES_PASSWORD=${MIKRO_ORM_PASSWORD}
      - POSTGRES_DB=${MIKRO_ORM_DB_NAME}
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
